### ISSUE TITLE
Package marker breaks GitHub actions on using pip>=24.0

### ISSUE THREAD

**Issue by MAKOMO** [yoctopuce/yoctolib_python#10]
The pylint GitHub actions of the [Artisan project](https://github.com/artisan-roaster-scope/artisan) started to fail once pip v24.1 was released. As this did not get fixed by the pip v24.1.1 I reported the issue: https://github.com/pypa/pip/issues/12825

The pip team analyzed the issue and found that it goes back to an [open upstream issue in pypa/packaging](https://github.com/pypa/packaging/issues/774).

The pip team then [added some better error logging](https://github.com/pypa/pip/pull/12829) which the revealed that the culprit is the yoctopuce package.

Although your marker package seems not contradict any rules (thus I am not an expert on packaging), if possible, it might be good if you could adjust the yoctopuce package marker to prevent this issue from occuring.

**Comment by diazona** [comment]
Hey @MAKOMO :wave: The thing about this bug is that the package marker causing the problem doesn't come from the package being depended on, but from the one that has it as a dependency. In this case, the source of the error is [where yoctopuce is listed in Artisan's own `requirements.txt` file](https://github.com/artisan-roaster-scope/artisan/blob/master/src/requirements.txt#L76). There isn't really anything that yoctopuce can or should do about this.

**Comment by MAKOMO** [comment]
Understood. So because the yoctopuce package is the first one being discriminated by sys_platform in our requirements.txt it is the point where pip >24.0 first fails. Thus closing this here and hoping for an upstream fix.
