### ISSUE TITLE
Can't connect with python, but can connect with VirtualHub.

### ISSUE THREAD

**Issue by spott** [yoctopuce/yoctolib_python#2]
`YGenericSensor.FirstGenericSensor() == None`, when a device is connected, and the VirtualHub still finds it.

I am on OS X Sierra, and I'm not sure how to debug this further.  This is a Thermistor-C module.

**Comment by yoctopuce** [comment]
Did you check the result of YAPI.RegisterHub ?  Remember, you can't have more one application  accessing the device in USB native mode at the same time. see: 
http://www.yoctopuce.com/EN/article/error-message-another-process-is-already-using-yapi

**Comment by yoctopuce** [comment]
The Thermistor-C has 6 Temperatures interface so you need to use the `YTemperature `class not the `YGenericSensor` class. 

**The right code is :** `YTemperature.FirstTemperature()`

Note: _You could also use the `YSensor` or `YFunction` class since `YTemperature` is a subclass of `YSensor` witch is a subclass of `YTemperature`. `YGenericSensor` it a class that is used in module that emulate a sensor from another protocol (ex Yocto-RS232, Yocto-4-20mA-Rx, Yocto-SPI, etc...)_

**Comment by spott** [comment]
Thank you very much.  I must have missed this in the documentation.
